#!/bin/bash


echo "Destroying local copies of /userspace"
echo ""
echo "Press any key to continue..."
readline -p
echo ""
rm -rfv userspace/*
#rm -rfv boot/*

cp -rvp mount.root/* userspace
#cp -rvp mount.boot/* boot
sync
