#!/bin/bash

base="novix"
arch="aarch64"
tag="latest"

name="${base}-${arch}-${tag}.img"
fqn="dist/${name}"
echo "Mounting ${name}"

d1start=$(fdisk -l -o "Start" ${fqn} | tail -2 | head -1)
d2start=$(fdisk -l -o "Start" ${fqn} | tail -2 | tail -1)

sectorSize=512

d1=$(($d1start * $sectorSize))
d2=$(($d2start * $sectorSize))

echo "Offset 1: ${d1}"
echo "Offset 2: ${d2}"

#mount -t vfat -o loop,offset=${d1} ${fqn} mount.boot
mount -t ext4 -o loop,offset=${d2} ${fqn} mount.root

