#!/bin/bash

base="novix"
arch="aarch64"
tag="latest"

name="${base}-${arch}-${tag}.img"
fqn="dist/${name}"
echo "Generating empty base ${name}"

wipefs -a ${fqn}
dd if=/dev/zero of=${fqn} bs=1 count=1 seek=1M

# build empty 8gb image
dd if=/dev/zero of=${fqn} bs=1 count=0 seek=8G

device="/dev/loop0"
echo "Building loop device ${device}"

#kpartx -d ${fqn}
#kpartx -a ${fqn}
#losetup
losetup -f --show ${fqn}
partx -a ${device}

#echo "Building partition table on ${device}"
#parted ${fqn} --script -- mklabel msdos
#parted ${fqn} --script -- mkpart primary fat32 1 1000
#parted ${fqn} --script -- mkpart primary ext4 1000 100%
#parted ${fqn} --script -- set 1 boot on
#parted ${fqn} --script print

#kpartx -u ${fqn}

mkfs.vfat ${device}p1
yes | mkfs.ext4 ${device}p2
