#!/bin/bash

cd linux

##
# Development kernels and their remotes
#
#asahi       git@github.com:AsahiLinux/linux.git (fetch)
git remote add asahi git@github.com:AsahiLinux/linux.git
#kris-nova   git@github.com:kris-nova/linux.git (fetch)
git remote add kris-nova git@github.com:kris-nova/linux.git
#soc         git://git.kernel.org/pub/scm/linux/kernel/git/soc/soc.git (fetch)
git remote add soc git://git.kernel.org/pub/scm/linux/kernel/git/soc/soc.git
#torvalds    git@github.com:torvalds/linux.git (fetch)
git remote add torvalds git@github.com:torvalds/linux.git
git remote add origin git@github.com:torvalds/linux.git

##
# Define the remote and branch
# to use for a checkout
#
remote="torvalds"
branch="master"

git remote -v
git checkout ${branch}
git pull ${remote} ${branch}
git reset --hard ${remote}/${branch}
make clean
