#!/bin/bash

##
# [Aarch64 Generic]
#
#tarball="http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz"

##
# [Aarch64 Rpi]
#
tarball="http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-aarch64-latest.tar.gz"


echo "Downloading..."
echo
echo "${tarball}"
echo

wget ${tarball} -O tar/base.tar.gz 