#!/bin/bash

echo "Compiling kernel..."

if [[ $EUID -ne 0 ]];then
    echo "Please run as root..."
    exit 1
fi

config="kernel.config.rpi4"
echo "Using: ${config}"
cp -v ${config} linux/arch/arm64/configs/novix_defconfig
cp -v ${config} linux/.config.old
cd linux

##
#
# nóvix compile kernel flags
#
# ------------------------------------------------

##
# Kernel compile command
make -j16 \
    ARCH=arm64 \
    CROSS_COMPILE=aarch64-linux-gnu- \
    novix_defconfig Image modules dtbs 

# ------------------------------------------------

