#!/bin/bash

if [ -z "$1" ]; then
   echo "usage: run-format /dev/sdN"
   exit 1
fi


umount ${1}1
umount ${1}2


parted ${1} --script -- mklabel msdos
parted ${1} --script -- mkpart primary fat32 1 1000
echo "${1}1 fat32 1 1000"
parted ${1} --script -- mkpart primary ext4 1000 100%
echo "${1}2 ext4 +1000 100%"
parted ${1} --script -- set 1 boot on
parted ${1} --script print

mkfs.vfat ${1}1
yes | mkfs.ext4 ${1}2

echo
echo "${1}1 [vfat]"
echo "${1}2 [ext4]"
echo
